# 3-6 More Guests
guests = ["Alice", "Bob", "Charlie"]
print(f"Hello, {guests[0]}! Please join me for dinner.")
print(f"Hello, {guests[1]}! Please join me for dinner.")
print(f"Hello, {guests[2]}! Please join me for dinner.")
print("I've found a bigger table!")
guests.insert(0, "David")
guests.insert(2, "Eve")
guests.append("Frank")
print(f"Hello, {guests[0]}! Please join me for dinner.")
print(f"Hello, {guests[1]}! Please join me for dinner.")
print(f"Hello, {guests[2]}! Please join me for dinner.")
print(f"Hello, {guests[3]}! Please join me for dinner.")
print(f"Hello, {guests[4]}! Please join me for dinner.")
print(f"Hello, {guests[5]}! Please join me for dinner.")
